### PR TITLE
Release 0.8.0

### PR DESCRIPTION
**Pull request by rbradford**
Signed-off-by: Rob Bradford <robert.bradford@intel.com>

### CODE REVIEW

**Comment by andreeaflorescu** [comment]
@rbradford I was thinking we can first publish kvm-bindings v0.4.0 and then relax this dependency. As you pointed out in your previous PR, it is a bit strange to use a fixed dependency that points to a previous release. What do you say?

**Comment by rbradford** [comment]
> @rbradford I was thinking we can first publish kvm-bindings v0.4.0 and then relax this dependency. As you pointed out in your previous PR, it is a bit strange to use a fixed dependency that points to a previous release. What do you say?

It would still need to be `>=0.4.0` as we don't anyone to every try it with 0.3.1 as it won't work.

**Comment by andreeaflorescu** [comment]
> > @rbradford I was thinking we can first publish kvm-bindings v0.4.0 and then relax this dependency. As you pointed out in your previous PR, it is a bit strange to use a fixed dependency that points to a previous release. What do you say?
> 
> It would still need to be `>=0.4.0` as we don't anyone to every try it with 0.3.1 as it won't work.

Yes. We would need to update the `Cargo.toml` of kvm-ioctls as well.

**Comment by rbradford** [comment]
kvm-bindings release PR: https://github.com/rust-vmm/kvm-bindings/pull/33 this will mean that the cloud-hypervisor & firecracker forks will need to be updated to have that newer version number.

**Comment by andreeaflorescu** [comment]
I've published the new version of kvm-bindings.

**Comment by rbradford** [comment]
> I've published the new version of kvm-bindings.

Thanks @andreeaflorescu this PR is updated.

**Review by andreeaflorescu — APPROVED** [review]

**Review by lauralt — APPROVED** [review]

**Review by alxiord — APPROVED** [review]

**Pull request merged**
