### PR TITLE
update usage of FAM struct

### LINKED ISSUE #138: Fix kvm-ioctls build after new vmm-sys-util update
There were some breaking interface changes in vmm-sys-util v0.8.0 in the handling of FAM struct.
These need to be addressed for the build to pass.

Example output of failing tests: https://buildkite.com/rust-vmm/kvm-ioctls-ci/builds/602

### PR DESCRIPTION
**Pull request by andreeaflorescu**
This patch is required because of the latest vmm-sys-util version.

Fixes: #138 

FAM Struct now returns a result on new. Check the result before
initializing the relevant structures.

PartialEq is no longer implemented for FAM structs where the inner type
does not implement PartialEq as well. As a consequence, we cannot test
for equality between Cpuid values.

### CODE REVIEW

**Review by acatangiu — DISMISSED** [review]

**Review by rbradford — APPROVED** [review]

**Comment by rbradford** [comment]
Doesn't the Cargo.toml need to be updated to reflect that the code is now using the new API?

**Comment by andreeaflorescu** [comment]
> Doesn't the Cargo.toml need to be updated to reflect that the code is now using the new API?

Do you mean updating the version of the crate or the version of the vmm-sys-util dependency?

**Comment by rbradford** [comment]
> > Doesn't the Cargo.toml need to be updated to reflect that the code is now using the new API?
> 
> Do you mean updating the version of the crate or the version of the vmm-sys-util dependency?

The version of the dependency on vmm-sys-util. The code here now depends on the newer behaviour.

**Review by jiangliu — APPROVED** [review]

**Comment by andreeaflorescu** [comment]
> > > Doesn't the Cargo.toml need to be updated to reflect that the code is now using the new API?
> > 
> > 
> > Do you mean updating the version of the crate or the version of the vmm-sys-util dependency?
> 
> The version of the dependency on vmm-sys-util. The code here now depends on the newer behaviour.

I'll create a PR for a new release of kvm-ioctls, and also update that.

**Comment by rbradford** [comment]
> > > > Doesn't the Cargo.toml need to be updated to reflect that the code is now using the new API?
> > > 
> > > 
> > > Do you mean updating the version of the crate or the version of the vmm-sys-util dependency?
> > 
> > 
> > The version of the dependency on vmm-sys-util. The code here now depends on the newer behaviour.
> 
> I'll create a PR for a new release of kvm-ioctls, and also update that.

That's cool, but in general it's probably better to try and update the Cargo.toml dependency at the same time as introducing the use of the changed API otherwise builds will break (since updating to a newer version of kvm-ioctls by git won't necessarily bring in the newer required vmm-sys-util depending on the Cargo.lock file and how it was updated.)

**Comment by andreeaflorescu** [comment]
> > I'll create a PR for a new release of kvm-ioctls, and also update that.
> 
> That's cool, but in general it's probably better to try and update the Cargo.toml dependency at the same time as introducing the use of the changed API otherwise builds will break (since updating to a newer version of kvm-ioctls by git won't necessarily bring in the newer required vmm-sys-util depending on the Cargo.lock file and how it was updated.)

Sounds good to me! It was an oversight. Generally we are not expecting all commits from master to be ready to be consumed though (at least not in production use cases).

**Pull request merged**
